'use strict';

const fs = require('fs/promises');
const path = require('path');

// ─── Helpers ────────────────────────────────────────────────────────────────

/**
 * Read all .md files from a directory and return their concatenated content.
 * Skips README.md files since those are directory documentation, not agent rules.
 * @param {string} dir
 * @returns {Promise<string>}
 */
async function readMarkdownDir(dir) {
  let content = '';
  try {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isFile() && entry.name.endsWith('.md') && entry.name !== 'README.md') {
        const filePath = path.join(dir, entry.name);
        const fileContent = await fs.readFile(filePath, 'utf-8');
        const section = entry.name.replace('.md', '').replace(/-/g, ' ');
        content += `\n## ${section}\n\n${fileContent}\n\n---\n`;
      }
    }
  } catch {
    // Directory may not exist; silently skip
  }
  return content;
}

/**
 * Ensure a directory exists, creating it if necessary.
 * @param {string} dirPath
 */
async function ensureDir(dirPath) {
  await fs.mkdir(dirPath, { recursive: true });
}

/**
 * Copy all files from a source directory to a destination directory.
 * @param {string} src
 * @param {string} dest
 */
async function copyDir(src, dest) {
  await ensureDir(dest);
  const entries = await fs.readdir(src, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.isFile()) {
      await fs.copyFile(
        path.join(src, entry.name),
        path.join(dest, entry.name)
      );
    }
  }
}

// ─── Cursor ──────────────────────────────────────────────────────────────────

/**
 * Sync .agents/rules/ → .cursor/rules/
 * @param {string} agentsDir
 * @param {string} cwd
 */
async function syncToCursor(agentsDir, cwd) {
  const src  = path.join(agentsDir, 'rules');
  const dest = path.join(cwd, '.cursor', 'rules');
  await copyDir(src, dest);
}

// ─── Claude ──────────────────────────────────────────────────────────────────

/**
 * Compile .agents/ into a single CLAUDE.md file.
 * @param {string} agentsDir
 * @param {string} cwd
 * @param {string} techStack
 */
async function syncToClaude(agentsDir, cwd, techStack) {
  const rulesContent    = await readMarkdownDir(path.join(agentsDir, 'rules'));

  const claudeMd = `# CLAUDE.md — AI Agent Instructions

> This file was auto-generated by [agentive](https://github.com/TiPS0/agentive).
> Edit the source files in \`.agents/\` and re-run \`npx @p_tipso/agentive\` to regenerate.

## Project Context

**Tech Stack:** ${techStack}

# Rules
${rulesContent}
`.trim();

  await fs.writeFile(path.join(cwd, 'CLAUDE.md'), claudeMd, 'utf-8');
}

// ─── Windsurf ────────────────────────────────────────────────────────────────

/**
 * Compile .agents/rules/ into a single .windsurfrules file.
 * @param {string} agentsDir
 * @param {string} cwd
 * @param {string} techStack
 */
async function syncToWindsurf(agentsDir, cwd, techStack) {
  const rulesContent    = await readMarkdownDir(path.join(agentsDir, 'rules'));

  const windsurfRules = `# .windsurfrules — AI Agent Instructions

> Auto-generated by [agentive](https://github.com/TiPS0/agentive).
> Edit \`.agents/\` and re-run \`npx @p_tipso/agentive\` to regenerate.

**Tech Stack:** ${techStack}

# Rules
${rulesContent}
`.trim();

  await fs.writeFile(path.join(cwd, '.windsurfrules'), windsurfRules, 'utf-8');
}

module.exports = { syncToCursor, syncToClaude, syncToWindsurf };
